import Head from 'next/head'
import DB from '../server/mongo/mongo.init'

export async function getServerSideProps(context) {
  const isConnected = await DB();
  return {
    props: {
      isConnected: isConnected ?? null
    }
  }
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
      </main>
    </div>
  )
}
