import Head from 'next/head'
import HomePage from '../client/components/pages/home/Home.page'
import ListPageLayout from '../client/Layouts/ListPageLayout'
import styles from "../styles/pages/Home.module.scss"

export default function Home() {
  return (
    <div className='h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage />
      </main>
    </div>
  )
}